import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: "normal",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-Poppins",
});

const gilroy = localFont({
  src: [
    {
      path: "./../font/Gilroy-ExtraBold.ttf",
      style: "normal",
      weight: "bold",
    },
    {
      path: "./../font/Gilroy-Light.ttf",
      style: "normal",
      weight: "normal",
    },
  ],
  variable: "--font-Gilroy",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${gilroy.variable} px-[3%]`}>
        <Navbar />
        <section className="flex flex-col md:flex-row gap-5">
          <main className="md:w-8/12 lg:w-9/12">{children}</main>
          <Sidebar />
        </section>
        <Footer />
      </body>
    </html>
  );
}
